---
- hosts: devlaptops
  tasks:
  - name: install java jdk
    apt:
      name: openjdk-8-jdk
  - name: install java jdk sources
    apt:
      name: openjdk-8-source
  - name: install groovy
    apt:
      name: groovy2
  - name: install git 
    apt:
      name: git
  - name: install curl
    apt:
      name: curl
  - name: install mysql client
    apt:
      name: mysql-client
  - name: download mysql jdbc driver
    apt:
      name: libmysql-java
  - name: install tomcat distribution
    apt:
      name: tomcat8
  - name: disable autostart for tomcat
    service:
      name: tomcat8
      state: stopped
      enabled: no
  - name: install mysql driver into tomcat
    file:
      path: /usr/share/tomcat8/lib/mysql-connector-java.jar
      src: /usr/share/java/mysql-connector-java.jar
      state: link
  - name: install apache ant
    apt:
      name: ant
  - name: install maven
    apt:
      name: maven
